# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNTinderCloneApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNTinderCloneApp
  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  target 'RNTinderCloneAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
